url: https://andyarcher.org
baseurl: ''

# Site settings
title: Andy Archer
email: andy.archer@yale.edu
description: "Body-based therapy, whole person healing."

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty